@startuml
title SmartDress - Class Diagram

left to right direction
skinparam classAttributeIconSize 0

class Member {
    +Integer id
    +String nom
    +String email
    +String motDePasse
    +String initiales
    +StatutUtilisateur statut
    +DateTime created_at
    +DateTime updated_at
}

class Role {
    +Integer id
    +String nom
    +String guard_name
    +DateTime created_at
    +DateTime updated_at
}

class Permission {
    +Integer id
    +String nom
    +String guard_name
    +DateTime created_at
    +DateTime updated_at
}

class Favori {
    +Integer id
    +DateTime dateAjout
}

class Tenue {
    +Integer id
    +String nom
    +DateTime dateCreation
    +DateTime datePlanifiee
}

class Vetement {
    +Integer id
    +String nom
    +CategorieVetement categorie
    +String couleur
    +String imageUrl
}

class Photo {
    +Integer id
    +String url
    +DateTime dateUpload
}

Member "*" -- "*" Role : possède

Member "1" -- "0..*" Tenue : crée


Vetement "1" -- "0..*" Favori : concerne

Role "*" -- "*" Permission : accorde

Tenue "1" -- "1..*" Vetement : composée_de
Vetement "1" -- "0..*" Photo : contient

@enduml