@startuml
skinparam actorStyle awesome
left to right direction

' STYLE CUSTOMIZATION
skinparam package {
    BackgroundColor White
    BorderColor #5C4A35
}
skinparam usecase {
    BackgroundColor #F5EEE4
    BorderColor #889063
    ArrowColor #889063
}

' ACTORS
actor "Administrateur" as A
actor "Serveur Web / IA" as W

' SYSTEM = MOBILE APP
package "SmartDress App (Mobile)" {

    usecase "S'authentifier via API" as UC_LOGIN_MOBILE

    package "Espace Administration" {
        usecase "Consulter les statistiques\net l'activité système" as UC_ADMIN_MOBILE
    }

    ' API part
    usecase "Interagir avec les services\n(Météo, IA, Stockage)" as UC_API_MOBILE
}

' ASSOCIATIONS
A -- UC_LOGIN_MOBILE
A -- UC_ADMIN_MOBILE

' Web server provides the API
UC_API_MOBILE -- W

' INCLUDES
UC_ADMIN_MOBILE ..> UC_LOGIN_MOBILE : <<include>>
UC_ADMIN_MOBILE ..> UC_API_MOBILE : <<include>>

@enduml