@startuml
skinparam actorStyle awesome
left to right direction
skinparam package {
    BackgroundColor White
    BorderColor #5C4A35
}
skinparam usecase {
    BackgroundColor #F5EEE4
    BorderColor #889063
    ArrowColor #889063
}

actor "Utilisateur" as U

package "Sprint 2 – Fonctionnalités Avancées (Utilisateur)" {

    package "Améliorations Utilisateur" {
        usecase "Recevoir notifications\nde planification" as UC1
        usecase "Vérifier météo en temps réel" as UC2
        usecase "Analyser préférences\nautomatiquement" as UC3
        usecase "Partager une tenue" as UC4
        usecase "Ajouter un commentaire\nsur une tenue" as UC5
    }

    U -- UC1
    U -- UC2
    U -- UC3
    U -- UC4
    U -- UC5

    UC2 ..> UC3 : <<include>>
}
@enduml
