@startuml
skinparam actorStyle awesome
left to right direction
skinparam package {
    BackgroundColor White
    BorderColor #5C4A35
}
skinparam usecase {
    BackgroundColor #F5EEE4
    BorderColor #889063
    ArrowColor #889063
}

actor "Administrateur" as Admin

package "Sprint 2 – Fonctionnalités Avancées (Administrateur)" {

    package "Améliorations Administrateur" {
        usecase "Consulter tableau de bord avancé" as UC6
        usecase "Voir statistiques détaillées\n(vêtements, tenues, users)" as UC7
        usecase "Modérer les commentaires" as UC8
        usecase "Contrôler le contenu publié" as UC9
    }

    Admin -- UC6
    Admin -- UC7
    Admin -- UC8
    Admin -- UC9

    UC6 ..> UC7 : <<include>>
}
@enduml
