@startuml
left to right direction

actor Administrateur

rectangle "SmartDress — Use Case Diagram (Administrateur)" {

  ' =========================
  ' AUTHENTIFICATION
  ' =========================
  usecase "Se connecter" as UC1
  usecase "Se déconnecter" as UC2

  Administrateur -- UC1
  Administrateur -- UC2


  ' =========================
  ' ADMINISTRATION
  ' =========================
  usecase "Gérer utilisateurs\n(Créer, Modifier,\nSupprimer, Consulter)" as UC3
  usecase "Consulter statistiques" as UC4
  usecase "Modérer contenu" as UC5

  Administrateur -- UC3
  Administrateur -- UC4
  Administrateur -- UC5

}

@enduml